# Generated by Django 4.0.4 on 2022-05-19 18:18

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('store', '0007_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.URLField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
