# Generated by Django 4.0.4 on 2022-05-20 22:34

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('store', '0010_alter_cartitem_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.URLField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
